spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: edge
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  edgex: localhost
  port: 8090
export:
  name: gw inst export
  ip: 127.0.0.1
  port: 1883
  publisher: gw inst
  user: user
  password: user
  topic: edgex